---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1003
      - PGID=1003
      - VERSION=docker
    volumes:
      - /data/plex/config:/config
      - /data/media/Videos/TVShows:/tv
      - /data/media/Videos/Movies:/movies
      - /data/plex/transcode:/transcode
    restart:
      always 



